# Generated by Django 4.1.5 on 2023-02-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='email',
            field=models.EmailField(default='del@gmail.com', max_length=50),
            preserve_default=False,
        ),
    ]
